=== How to integrate Dear ImGui Bundle into your {cpp} application

This template demonstrates how to easily integrate Dear ImGui Bundle to your own project.

You can use it as a starting point for your own project.

Template repository: https://github.com/pthom/imgui_bundle_template


=== CMake

By default, you do not need to add imgui_bundle as a dependency to your project, it will be downloaded and built automatically during CMake configure time.

The link:CMakeLists.txt[CMakeLists.txt] file

* Downloads imgui_bundle at configure time
* Makes the `imgui_bundle_add_app` cmake function available
* Uses `imgui_bundle_add_app` to build your app and link it with ImGuiBundle

_Note: imgui_bundle_add_app will automatically link your app to imgui_bundle, and will embed the assets folder (for desktop, mobile, and emscripten apps)_


=== Assets

Anything in the assets/ folder located beside the app's CMakeLists will be bundled together with the app (for macOS, iOS, linux, emscripten).

The files in assets/app_settings/ will be used to generate the app icon, and the app settings.

[source]
----
assets/
├── world.png                   # A custom asset
│
├── app_settings/               # Application settings
│    ├── icon.png               # This will be the app icon, it should be square
│    │                          # and at least 256x256. It will  be converted
│    │                          # to the right format, for each platform (except Android)
│    ├── apple/
│    │    ├── Info.plist        # macOS and iOS app settings
│    │    │                      # (or Info.ios.plist + Info.macos.plist)
│    │    └── Resources/
│    │         └── ios/          # iOS specific settings: storyboard
│    │             └── LaunchScreen.storyboard
│    ├── android/                # Android app settings: any file placed here will be deployed
│    │   │── AndroidManifest.xml # (Optional manifest, HelloImGui will generate one if missing)
│    │   └── res/
│    │       └── mipmap-xxxhdpi/ # Optional icons for different resolutions
│    │           └── ...         # Use Android Studio to generate them:
│    │                           # right click on res/ => New > Image Asset
│    │
│    └── emscripten/
│        ├── shell.emscripten.html # Emscripten shell file
│        │                         #   (this file will be cmake "configured"
│        │                         #    to add the name and favicon)
│        └── custom.js             # Any custom file here will be deployed
│                                  #   in the emscripten build folder
│
├── fonts/
│    ├── DroidSans.ttf           # Default fonts
│    └── fontawesome-webfont.ttf #     used by HelloImGui
│    ├── Roboto
│    │    ├── Roboto-Bold.ttf        # Font used by Markdown
│    │    ├── Roboto-BoldItalic.ttf
│    │    ├── Roboto-Regular.ttf
│    │    └── Roboto-RegularItalic.ttf
│    ├── SourceCodePro-Regular.ttf
├── images
│    └── markdown_broken_image.png

----


=== Main cpp file

The link:hello_world.cpp[hello_world.cpp] file

* Provides a Gui function which is executed at each frame
* Provides a main function that set the ImmApp ("Immediate App") params, and mentions the addons we intend to use (here we are using markdown and implot).

=== Build instructions

==== Build for Linux and macOS

===== 1. Optional: clone imgui_bundle

_Note: This step is optional, since the CMakeLists.txt file will by default download and build imgui_bundle at configure time._

In this example, we clone imgui_bundle inside `external/imgui_bundle`.

Note: `external/` is mentioned in `.gitignore`

[source, bash]
----
mkdir -p external && cd external
git clone https://github.com/pthom/imgui_bundle.git
cd imgui_bundle && git submodule update --init --recursive
cd ../..
----


Add this line at the top of your CMakeLists.txt

[source, cmake]
----
add_subdirectory(external/imgui_bundle)
----

===== 2. Create the build directory, run cmake and make

[source, bash]
----
mkdir -p build && cd build
cmake ..
make -j 4
----

==== Build for Windows

===== 1. Optional: clone imgui_bundle
Follow step 1 from the Linux/macOS section above.

===== 2. Create the build directory, run cmake

[source, bash]
----
mkdir build && cd build
cmake ..
----

===== 3. Open the Visual Studio solution
It should be located in build/imgui_bundle_example_integration.sln


==== Build for emscripten

===== Install emscripten
You can either install emsdk following link:https://emscripten.org/docs/getting_started/downloads.html[the instruction on the emscripten website].

===== Compile with emscripten

[source, bash]
----
# Add emscripten tools to your path
# (assuming you installed emscripten in ~/emsdk)
source ~/emsdk/emsdk_env.sh

# cmake and build
mkdir build_emscripten
cd build_emscripten
emcmake cmake ..
make -j 4

# launch a webserver
python3 -m http.server
----

Open a browser, and navigate to [http://localhost:8000](http://localhost:8000).
